networks:
  react-express:
services:
  frontend:
    build:
      context: circle-frontend
    ports:
      - 3000:3000
    stdin_open: true
    restart: always
    depends_on:
      - backend
    networks:
      - react-express
  backend:
    restart: always
    build:
      context: circle-backend
    ports:
      - 9000:9000
    networks:
      - react-express

  # mongo:
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${mongo_username}
  #     MONGO_INITDB_ROOT_PASSWORD: ${mongo_password}
  #   volumes:
  #     - ./volumes/mongo-data:/data/db

  # mongo-express:
  #   image: mongo-express:latest
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${mongo_username}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${mongo_password}
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #     ME_CONFIG_BASICAUTH: true
  #     ME_CONFIG_BASICAUTH_USERNAME: ${express_username}
  #     ME_CONFIG_BASICAUTH_PASSWORD: ${express_password}
  #   depends_on:
  #     - mongo
